### ISSUE TITLE
1주차 과제 TODO 리스트

### ISSUE THREAD

**Issue by JunHoPark93** [JunHoPark93/java-baseball#3]
- [x] 기능 요구사항을 만족하였는가?
- [x] 프로그래밍 요구사항을 만족하였는가?
- [x] 과제 진행 요구사항을 만족하였는가?
